baseURL = 'https://drewku.com'
languageCode = 'en-us'
title = 'Drew Ku | Blog'
theme = 'PaperMod'
bind = "0.0.0.0"
paginate = 10
ShowToc = true
env = 'production'
enableemoji = true

[params]
ShowShareButtons = true
ShareButtons = [ "linkedin", "twitter" ]
ShowReadingTime = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true

[params.assets]
disableHLJS = true
favicon = "/root/hugo-site/resources/_gen/assets/android-icon-192x192.png"
favicon16x16 = "/root/hugo-site/resources/_gen/assets/favicon-16x16.png"
favicon32x32 = "/root/hugo-site/resources/_gen/assets/favicon-32x32.png"
apple_touch_icon = "/root/hugo-site/resources/_gen/assets/android-icon-192x192.png"
safari_pinned_tab = "/root/hugo-site/resources/_gen/assets/apple-startup-1182x2208.png"

[params.homeInfoParams]
Title = "Hi there. I'm Andrew 👋"
Content = "I'm a cloud engineer by day, and this is where my thoughts are gathered."

[[params.socialIcons]]
name = "github"
url = "https://github.com/Drookoo"

[[params.socialIcons]]
name = "youtube"
url = "https://www.youtube.com/DrewKu"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/drookoo"



[outputs]
home = ["HTML", "RSS", "JSON"]

[languages.en]
languageName = "English"
weight = 1

  [languages.en.taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[[languages.en.menu.main]]
name = "Search"
url = "search/"
weight = 10

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 10

