name: Trigger Git Pull on Downstream Runner
on:
  push:
    branches:
      - 'main'
jobs:
  auto-pull:
    name: GitPullDownstream
    if: github.repository == 'Drookoo/hugo-site'
    runs-on: self-hosted
    steps:
      -
        name: gitpull
        run: |
          git config --global --add safe.directory /andrew/hugo-site
          git pull origin main
        working-directory: /andrew/hugo-site/
    

